### Trending Events

GET http://localhost:3000/trendingEvents

### Trending Events with limit and offset

GET http://localhost:3000/trendingEvents?limit=10&offset=10

### This Week Events with limit and offset

GET http://localhost:3000/thisweekevents?limit=10&offset=0

### Upcoming Events with limit and offset

GET http://localhost:3000/upcomingevents?limit=10&offset=0